---
title: 'Lab: Decision Trees'
author: "Dilawar Mahmood"
date: "May 06, 2021"
output:
  html_document:
    df_print: paged
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
showsolA<-TRUE
showsolB<-TRUE
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=68),tidy=TRUE)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE,
                      cache=TRUE, size="scriptsize")
whichformat="html"
```

```{r}
library(MASS)
library(ISLR)
library(tree)
```

```{r}
set.seed(1)
train = sample(1:nrow(Boston), nrow(Boston)/2)
head(Boston)
tree.boston = tree(medv~., Boston, subset=train)
summary(tree.boston)
```

```{r}
plot(tree.boston)
text(tree.boston, pretty=0)
```

```{r}
cv.boston = cv.tree(tree.boston)
plot(cv.boston$size, cv.boston$dev, type="b")
```

```{r}
prune.boston = prune.tree(tree.boston, best=5)
plot(prune.boston)
text(prune.boston, pretty=0)
```

```{r}
yhat=predict(tree.boston, newdata=Boston[-train, ])
boston.test=Boston[-train, "medv"]
plot(yhat, boston.test)+abline(0,1)
```

```{r}
mean((yhat-boston.test)^2)
```

```{r}
library(randomForest)
set.seed(1)
bag.boston = randomForest(medv~., data=Boston, subset=train, mtry=13, importance=TRUE)
bag.boston
```

```{r}
yhat.bag = predict(bag.boston, newdata=Boston[-train, ])
mean((yhat.bag - boston.test)^2)
```

```{r}
set.seed(1)
rf.boston = randomForest(medv~., data = Boston, subset=train, mtry=6, importance=TRUE)
yhat.rf = predict(rf.boston, newdata=Boston[-train, ])
mean((yhat.rf-boston.test)^2)
```

```{r}
importance(rf.boston)
```

```{r}
varImpPlot(rf.boston)
```

```{r}
library(gbm)
set.seed(1)
boost.boston = gbm(medv~., data=Boston[train, ], distribution="gaussian", n.trees=5000, interaction.depth=4)
```

```{r}
summary(boost.boston)
```

```{r}
par(mfrow=c(1,2))
plot(boost.boston, i="rm")
plot(boost.boston, i="lstat")
```

```{r}
yhat.boost = predict(boost.boston, newdata=Boston[-train, ], n.trees=5000)
mean((yhat.boost-boston.test)^2)
```

```{r}
boost.boston = gbm(medv~., data=Boston[train, ], distribution="gaussian", n.trees=5000, interaction.depth=4, shrinkage=0.2, verbose=F)
yhat.boost = predict(boost.boston, newdata=Boston[-train, ], n.trees=5000)
mean((yhat.boost-boston.test)^2)
```