---
title: 'Lab: Linear Regression'
author: "Dilawar Mahmood"
date: "April 30, 2021"
output:
  html_document:
    df_print: paged
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
showsolA<-TRUE
showsolB<-TRUE
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=68),tidy=TRUE)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE,
                      cache=TRUE, size="scriptsize")
whichformat="html"
```

# Libraries

```{r}
library(MASS)
library(ISLR)
```

# Simple Linear Regression

```{r}
fix(Boston)
names(Boston)
```

```{r}
lm.fit=lm(medv~lstat, data=Boston)
attach(Boston)
lm.fit=lm(medv~lstat)
```

```{r}
lm.fit
summary(lm.fit)
```

```{r}
names(lm.fit)
```

```{r}
confint(lm.fit)
```

```{r}
predict(lm.fit, data.frame(lstat=c(5,10,15)), interval="confidence")
predict(lm.fit, data.frame(lstat=c(5,10,15)), interval="prediction")
```

```{r}
plot(lstat, medv)
abline(lm.fit)
```

```{r}
plot(lstat, medv)
abline(lm.fit, lwd=3)
abline(lm.fit, lwd=3, col="red")
plot(lstat, medv, col="red")
plot(lstat, medv, pch=20)
plot(lstat, medv, pch="+")
plot(1:20, 1:20, pch=1:20)
```

```{r}
par(mfrow=c(2,2))
plot(lm.fit)
```

```{r}
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
```

```{r}
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
```

# Multiple Linear Regression

```{r}
lm.fit=lm(medv~lstat+age, data=Boston)
summary(lm.fit)
```

```{r}
lm.fit=lm(medv~., data=Boston)
summary(lm.fit)
```

```{r}
library(car)
vif(lm.fit)
```

```{r}
lm.fit1=lm(medv~.-age, data=Boston)
summary(lm.fit1)
lm.fit1=update(lm.fit, ~.-age)
```

# Interaction Terms

```{r}
summary(lm(medv~lstat*age, data=Boston))
```

# Non-linear Transformations of the Predictors

```{r}
lm.fit2=lm(medv~lstat+I(lstat^2))
summary(lm.fit2)
```

```{r}
lm.fit=lm(medv~lstat)
anova(lm.fit, lm.fit2)
```

```{r}
par(mfrow=c(2,2))
plot(lm.fit2)
```

```{r}
lm.fit5=lm(medv~poly(lstat, 5))
summary(lm.fit5)
```

```{r}
summary(lm(medv~log(rm), data=Boston))
```

# Qualitative Predictors

```{r}
fix(Carseats)
names(Carseats)
```

```{r}
lm.fit=lm(Sales~.+Income:Advertising+Price:Age, data=Carseats)
summary(lm.fit)
```

```{r}
attach(Carseats)
contrasts(ShelveLoc)
```

# Writing Functions

```{r}
LoadLibraries=function(){
  library(ISLR)
  library(MASS)
  print("The libraries have been loaded.")
}
```

```{r}
LoadLibraries()
```